### ISSUE TITLE
Many Problems Encountered During Execution

### ISSUE THREAD

**Issue by xcc-1921** [xssstory/STAS#6]
Hello author, I recently came across your paper and have been attempting to reproduce your process. However, I have encountered numerous unexpected problems and hope that you can assist me. 

I do not have much personal experience in this area.

After downloading the model, I entered the Evaluation step, but encountered issues when trying to run "bash extract_nyt.sh".

The main problem I am facing now is that during execution, there are many errors related to the 'data' folder. Could you please tell me specifically what is needed in the folder, especially the requested txt files and dataset (I only found one txt file here)?

Furthermore, some of the code has been deprecated by other developers, which requires downgrading the version of the library to run properly. (I apologize for forgetting which library and the error code; I believe it was an error in ensemble.py.)

I understand that my running environment is different from yours, as I am running your code on win10+cygwin64, which may lead to some problems. 

However, I have reviewed many resources and still do not understand what is in the 'data' folder. 

Could you please guide me? Thank you.

**Comment by xssstory** [comment]
You should split your data into train/validation/test subsets and get 6 files like train.article, train.summary, valid.article, valid.summary, test.article and test.summary, and ensure each line has one article/summary, and the sentence in the article/summary is split by "<S_SEP>". (we only use summaries for evaluation and test). For example, extract_nyt.sh requires data/nyt/valid.article and data/nyt/test.article. Please also refer to the **data preprocess** section to generate data/nyt/roberta_base_bin. If you are looking for the NYT dataset, I think you can refer to [(https://github.com/mswellhao/PacSum)](https://github.com/mswellhao/PacSum).

We run the code on the Ubuntu system. If you are familiar with docker, we have released the docker image. You can pull the docker image using ``docker pull xssstory/stas:latest``

**Comment by xcc-1921** [comment]
> 


Thank you very much. My program should be running normally now. As long as I modify some of the links in the .sh file, it should run basically normally in my environment. I may still have some issues, so should I leave this problem open for now?
